# Generated by Django 4.0.5 on 2022-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_map', models.JSONField()),
                ('file', models.FileField(upload_to='', verbose_name='datasource/')),
                ('model', models.CharField(max_length=50)),
            ],
        ),
    ]
